/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.worldedit.reziser;

import de.jan9103.wargearcore.worldedit.clip.Clipboard;
import de.jan9103.wargearcore.worldedit.clip.ClipboardBlock;

public class Multiplier extends Reziser {
	private final int xa,ya,za;
	public Multiplier(Clipboard cb,int xamount,int yamount,int zamount){
		super(cb);
		xa=Integer.max(1,xamount);
		ya=Integer.max(1,yamount);
		za=Integer.max(1,zamount);
	}

	@Override public Clipboard run(){
		if(xa+ya+za==3) return in;

		out=new Clipboard(in.xSize()*xa,in.ySize()*ya,in.zSize()*za);
		for(int x=0; x<in.xSize(); x++)
			for(int y=0; y<in.ySize(); y++)
				for(int z=0; z<in.zSize(); z++){
					final ClipboardBlock b=in.get(x,y,z);
					for(int xb=0; xb<xa; xb++)
						for(int yb=0; yb<ya; yb++)
							for(int zb=0; zb<za; zb++)
								out.set(x*xa+xb,y*ya+yb,z*za+zb,b);
				}
		return out;
	}
}
