/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.java.utils.json;

import java.util.ArrayList;

public class JsonArray extends ArrayList<Json>implements Json{
	private static final long serialVersionUID=-6605567872497773589L;
	@Override public Json jq(String[]a,int i)throws JqException{
		if(i==a.length)return this;
		switch(Character.toLowerCase(a[i].charAt(0))){
			case'[':
				if(a[i].length()==2)return jqAll(a,i);
				return jqInd(a[i].substring(1,a[i].length()-2),a,i);
			case'*':return jqAll(a,i);
			default:return jqInd(a[i],a,i);
		}
	}
	private Json jqInd(String ind,String[]a,int i)throws JqException{
		int in;
		try{in=Integer.parseInt(ind);
		}catch(NumberFormatException e){throw new JqException("Unknown jq action: "+a[i],a,i);}
		i++;
		if(in>=size())return null;
		return get(in).jq(a,i);
	}
	private Json jqAll(String[]a,int i)throws JqException{
		i++;
		JsonArray o=new JsonArray();
		for(Json j:this)o.add(j.jq(a,i));
		return o;
	}
	@Override public String encode(){
		StringBuilder o=new StringBuilder("[");
		boolean a=false;
		for(Json i:this){
			if(a)o.append(',');
			else a=true;
			o.append(i.encode());
		}
		return o.append(']').toString();
	}
	public String[]asStringArr()throws ClassCastException{
		String[]o=new String[this.size()];
		for(int i=0;i<this.size();i++)
			o[i]=((JsonValue)this.get(i)).asStr();
		return o;
	}
	public Double[]asDoubleArr()throws ClassCastException{
		Double[]o=new Double[this.size()];
		for(int i=0;i<this.size();i++)
			o[i]=((JsonValue)this.get(i)).asDouble();
		return o;
	}
	public Integer[]asIntArr()throws ClassCastException{
		Integer[]o=new Integer[this.size()];
		for(int i=0;i<this.size();i++)
			o[i]=((JsonValue)this.get(i)).asInt();
		return o;
	}
	public Object[]asValueArr()throws ClassCastException{
		Object[]o=new Object[this.size()];
		for(int i=0;i<this.size();i++)
			o[i]=((JsonValue)this.get(i)).value;
		return o;
	}
}
