/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.chat;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.ArrayList;

import org.bukkit.Bukkit;
import org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer;
import org.bukkit.entity.Player;

import de.jan9103.wargearcore.User;
import de.jan9103.wargearcore.WGC;
import de.jan9103.wargearcore.area.WgArea;
import de.jan9103.wargearcore.util.Flag;
import de.jan9103.wargearcore.util.TPS;

public class JoinMsgPanel {
	//TODO continue
	//TODO link

	private String motd="";
	private Flag flag  =null;
	public JoinMsgPanel(User u){
		final LocalDate ld   =LocalDate.now();
		int             i    =(int)(System.currentTimeMillis()%4);
		int             event=0;

		switch(ld.getMonthValue()){
		case 1:        //JAN
			switch(ld.getDayOfMonth()){
			case 1: motd="Happy new Year!"; break;

			case 7: motd="__WGL_2018__"; break;

			case 9: motd="Hello World!"; break;

			case 18: motd=(ld.getYear()-2015)+" years since Sandman.."; break;

			case 28: motd="Today is data protection day."; break;
			}
			break;

		case 2:        //FEB
			switch(ld.getDayOfMonth()){
			case 6: motd="WGL-2016 anniversary."; break;

			case 23: event=16; break;

			case 26: motd="WargearWorld was founded "+(ld.getYear()-2020)+" year ago."; break;
			}
			break;

		case 3:                                                               //MAR
			switch(ld.getDayOfMonth()){
			case 1: motd="International Zero Discrimination Day."; break; //TODO pride flag

			case 31:
				event=3;
				motd =".:WGL 2017:."; break;
			}
			break;

		case 4:        //APR
			switch(ld.getDayOfMonth()){
			case 1:
				switch(i){
				case 0: motd="Happy Birthday!"; break;

				case 1: motd="Mojang moved the crosshair there -> §r\u22B9"; break;

				case 2: motd="Half-Life 3 has been announced!"; break;

				case 3: motd="MCIV is coming back!"; event=17; break;
				}

			case 6:
				event=8;
				switch(i){
				case 0: motd="\u2660"; break;

				case 1: motd="Watch out denmark!"; break;

				case 2: motd="ever heard of Garlic Bread?"; break;

				case 3: motd="International Ace Day ;)"; break;
				}

			case 16: motd="MCIV v1 is now "+(ld.getYear()-2012)+" years old."; event=17; break;

			case 26: event=6; motd="Today is the Lesbian visibility day. \u2640\u2640"; break;             //2 female symbols
			}
			break;

		case 5:        //MAY
			switch(ld.getDayOfMonth()){
			case 6: motd=(ld.getYear()-2014)+"th Birthday of MPP"; break;

			case 17:
				switch(i){
				case 0: motd=(ld.getYear()-2019)+"th birthday of steamwar.de"; break;                      //TODO steamwar flag

				case 1: event=2; motd="Internation day against Biphobia"; break;

				case 2: event=3; motd="Internation day against Transphobia"; break;

				case 3: event=1; motd="Internation day against Homophobia"; break;
				}

			case 19: event=7; motd="Agender Pride Day!"; break;

			case 24: event=4; motd="Today is Pan awareness day."; break;

			case 27: {int z=2021-ld.getYear(); motd=z+" year"+(z>1?"s":"")+" ago WGC Closed Beta v1 was released.";} break;

			case 29: motd="Gear Forge opened "+(ld.getYear()-2015)+" years ago."; break;
			}
			break;

		case 6:        //JUN
			switch(ld.getDayOfMonth()){
			case 26: motd="Happy "+(ld.getYear()-1999)+"th."; break;
			}
			break;

		case 7:        //JUL
			switch(ld.getDayOfMonth()){
			case 14: event=5; motd="There are more than 2 gender!"; break;

			case 16: event=3; if(i==0) motd="Happy drag day"; break;            //TODO drag pride flag
			}
			break;

		case 8:                                           //AUG
			switch(ld.getDayOfMonth()){
			case 1: motd="\u25D5\u203F\u25D5"; break; //VOL logo

			case 22: motd=(ld.getYear()-2014)+" years ago.."; break;

			case 28: motd="#Stevia"; break;
			}
			break;

		case 9:        //SEP
			switch(ld.getDayOfMonth()){
			case 18: motd="Alpha Falcons go!"; break;

			case 21: motd="youtube.com/watch?v=vGiHuyfJKj0"; event=18; break;             //TODO csv4 tut? else change flag

			case 23: motd="Today is CBD!"; event=2; break;
			}
			break;

		case 10:        //OCT
			switch(ld.getDayOfMonth()){
			case 3: motd="many years ago a wall broke - be happy!"; break;

			case 8: motd="international lesbian day"; event=6; break;

			case 11: motd="Today would be a good day to come out.."; event=1; break;

			case 26: if(i==0) motd="Intersex exists."; event=12; break;
			}
			break;

		case 11:        //NOV
			switch(ld.getDayOfMonth()){
			case 20: motd="Internation Transgender day of Remembrance."; event=3; break;
			}
			break;

		case 12:        //DEC
		}
		if(motd=="")
			if(ld.getDayOfWeek()==DayOfWeek.FRIDAY){
				if(ld.getDayOfMonth()==13) motd="Friday the 13th ._.";
				else motd="Weekend!";
			}
		if(motd=="")
			switch(ld.getMonthValue()){
			case 6: if(i==0) motd="happy pride month!"; break;

			case 8: if(i==0) motd="\u2600"; break;     //SUN

			case 12:
				if(i==0) motd="\u2603"; break;      //SNOWMAN
			}
		//if(flag==null)flag=new Flag(0,u.ct,u.pre16);
		if(WGC.flagtext=="WGC")
			flag=new Flag(event,u.ct,u.pre16);
		else
			flag=new Flag(WGC.flagtext,event,u.ct,u.pre16);
	}

	public void send(User u,Player p){
		ArrayList<Player>ps=new ArrayList<>(Bukkit.getOnlinePlayers());
		final Msg        m =new Msg(u,null).aC("WGC CB-"+WGC.VERSION+" (made by Jan9103)",Msg.URL,"https://discord.gg/ddB2MDK","Join the official Discord-Server")
				     .a("\nPing: ").b(((CraftPlayer)p).getHandle().ping+"")
				     .a("\nTPS: ").b(TPS.b())
				     .a("\nloaded Areas: ").b(WgArea.areas.size()+"")
				     .a("\n\n\n");

		//TODO artwork / info combo
		m.insertJson(flag.a(0)).b("  "+WGC.servername);
		m.insertJson(flag.a(1)).a(" Online: ").b(ps.size()+"");
		m.insertJson(flag.a(2)); if(ps.size()>0) m.a("  - "+ps.get(0).getName());
		m.insertJson(flag.a(3)); if(ps.size()>1) m.a("  - "+ps.get(1).getName());
		m.insertJson(flag.a(4)); if(ps.size()>2) m.a("  - "+ps.get(2).getName());
		m.insertJson(flag.a(5)); if(ps.size()>3) m.a("  - "+ps.get(3).getName());
		m.insertJson(flag.a(6)); if(ps.size()>4) m.a("  - "+ps.get(4).getName());
		m.insertJson(flag.a(7)); if(ps.size()>5) m.a("  - "+ps.get(5).getName());
		m.insertJson(flag.a(8)); if(ps.size()>6) m.a("  - "+ps.get(6).getName());
		m.insertJson(flag.a(9)); if(ps.size()>8) m.a("  - ..."); else if(ps.size()>7) m.a("  - "+ps.get(7).getName());
		m.insertJson(flag.a(10)).a(motd);
		m.a(p);
	}
}
