/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.chat;

import org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer;
import org.bukkit.entity.Player;

import de.jan9103.wargearcore.User;
import de.jan9103.wargearcore.WGC;
import net.minecraft.server.v1_15_R1.IChatBaseComponent;
import net.minecraft.server.v1_15_R1.IChatBaseComponent.ChatSerializer;
import net.minecraft.server.v1_15_R1.PacketPlayOutChat;

public class Msg {
	public static final String RUN="run_command",SUGGEST="suggest_command",URL="open_url",COPY="copy_to_clipboard";
	private StringBuilder e;
	private final String[] f;
	public Msg(User a){
		e=new StringBuilder("[\"\",{\"text\":\""+ChatColor.a(a.ct,WGC._PREFIX_1,WGC._PREFIX_2_Core)+"\"}"); f=ChatColor.b(a.ct,a.pre16);
	}

	public Msg(User a,String b){
		e=new StringBuilder("[\"\""); if(b!=null) e.append(",{\"text\":\""+ChatColor.a(a.ct,WGC._PREFIX_1,b)+"\"}"); f=ChatColor.b(a.ct,a.pre16);
	}

	public Msg(User a,String b,String c){
		e=new StringBuilder("[\"\",{\"text\":\""+ChatColor.a(a.ct,b,c)+"\"}"); f=ChatColor.b(a.ct,a.pre16);
	}

	@Deprecated public String a(){
		return build();
	}

	public void a(Player p){
		send(p,build());
	}

	public void a(User u){
		final Player p=u.getPlayer(); if(p!=null) send(p,build());
	}

	public boolean hasNewLine(){
		return e.indexOf("\n")>0;
	}

	private void send(Player p,String s){
		final IChatBaseComponent comp=ChatSerializer.a(s);
		final PacketPlayOutChat  chat=new PacketPlayOutChat(comp);

		((CraftPlayer)p).getHandle().playerConnection.sendPacket(chat);
	}

	/**NORMAL*/
	public Msg aC(String txt,String clicktype,String clickdata,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"clickEvent\":{\"action\":\""+clicktype+"\",\"value\":\""+clickdata+"\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[0]+"}"); return this;
	}

	/**NORMAL*/
	public Msg aC(String txt,String clicktype,String clickdata){
		e.append(",{\"text\":\""+txt+"\",\"clickEvent\":{\"action\":\""+clicktype+"\",\"value\":\""+clickdata+"\"}"+f[0]+"}"); return this;
	}

	/**NORMAL*/
	public Msg aI(String txt,String insert,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"insertion\":\""+insert+"\",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[0]+"}"); return this;
	}

	/**NORMAL*/
	public Msg aI(String txt,String insert){
		e.append(",{\"text\":\""+txt+"\",\"insertion\":\""+insert+"\""+f[0]+"}"); return this;
	}

	/**NORMAL*/
	public Msg a(String txt){
		e.append(",{\"text\":\""+txt+"\""+f[0]+"}"); return this;
	}

	/**NORMAL*/
	public Msg a(String txt,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"hoverEvent\":{\"action:\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[0]+"}"); return this;
	}

	/**HIGHLIGHT*/
	public Msg cC(String txt,String clicktype,String clickdata,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"clickEvent\":{\"action\":\""+clicktype+"\",\"value\":\""+clickdata+"\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[1]+"}"); return this;
	}

	/**HIGHLIGHT*/
	public Msg cC(String txt,String clicktype,String clickdata){
		e.append(",{\"text\":\""+txt+"\",\"clickEvent\":{\"action\":\""+clicktype+"\",\"value\":\""+clickdata+"\"}"+f[1]+"}"); return this;
	}

	/**HIGHLIGHT*/
	public Msg cI(String txt,String insert,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"insertion\":\""+insert+"\",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[1]+"}"); return this;
	}

	/**HIGHLIGHT*/
	public Msg cI(String txt,String insert){
		e.append(",{\"text\":\""+txt+"\",\"insertion\":\""+insert+"\""+f[1]+"}"); return this;
	}

	/**HIGHLIGHT*/
	public Msg c(String txt){
		e.append(",{\"text\":\""+txt+"\""+f[1]+"}"); return this;
	}

	/**HIGHLIGHT*/
	public Msg c(String txt,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"hoverEvent\":{\"action:\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[1]+"}"); return this;
	}

	/**INVALID*/
	public Msg bC(String txt,String clicktype,String clickdata,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"clickEvent\":{\"action\":\""+clicktype+"\",\"value\":\""+clickdata+"\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[2]+"}"); return this;
	}

	/**INVALID*/
	public Msg bC(String txt,String clicktype,String clickdata){
		e.append(",{\"text\":\""+txt+"\",\"clickEvent\":{\"action\":\""+clicktype+"\",\"value\":\""+clickdata+"\"}"+f[2]+"}"); return this;
	}

	/**INVALID*/
	public Msg bI(String txt,String insert,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"insertion\":\""+insert+"\",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[2]+"}"); return this;
	}

	/**INVALID*/
	public Msg bI(String txt,String insert){
		e.append(",{\"text\":\""+txt+"\",\"insertion\":\""+insert+"\""+f[2]+"}"); return this;
	}

	/**INVALID*/
	public Msg b(String txt){
		e.append(",{\"text\":\""+txt+"\""+f[2]+"}"); return this;
	}

	/**INVALID*/
	public Msg b(String txt,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"hoverEvent\":{\"action:\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[2]+"}"); return this;
	}

	/**FRAME*/
	public Msg d(String txt){
		e.append(",{\"text\":\""+txt+"\""+f[6]+"}"); return this;
	}

	/**FRAME*/
	public Msg d(){
		e.append(",{\"text\":\"\n| \""+f[6]+"}"); return this;
	}

	/**ERROR*/
	public Msg eC(String txt,String clicktype,String clickdata,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"clickEvent\":{\"action\":\""+clicktype+"\",\"value\":\""+clickdata+"\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[3]+"}"); return this;
	}

	/**ERROR*/
	public Msg eC(String txt,String clicktype,String clickdata){
		e.append(",{\"text\":\""+txt+"\",\"clickEvent\":{\"action\":\""+clicktype+"\",\"value\":\""+clickdata+"\"}"+f[3]+"}"); return this;
	}

	/**ERROR*/
	public Msg eI(String txt,String insert,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"insertion\":\""+insert+"\",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[3]+"}"); return this;
	}

	/**ERROR*/
	public Msg eI(String txt,String insert){
		e.append(",{\"text\":\""+txt+"\",\"insertion\":\""+insert+"\""+f[3]+"}"); return this;
	}

	/**ERROR*/
	public Msg e(String txt){
		e.append(",{\"text\":\""+txt+"\""+f[3]+"}"); return this;
	}

	/**ERROR*/
	public Msg e(String txt,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"hoverEvent\":{\"action:\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[3]+"}"); return this;
	}

	/**WARN*/
	public Msg fC(String txt,String clicktype,String clickdata,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"clickEvent\":{\"action\":\""+clicktype+"\",\"value\":\""+clickdata+"\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[5]+"}"); return this;
	}

	/**WARN*/
	public Msg fC(String txt,String clicktype,String clickdata){
		e.append(",{\"text\":\""+txt+"\",\"clickEvent\":{\"action\":\""+clicktype+"\",\"value\":\""+clickdata+"\"}"+f[5]+"}"); return this;
	}

	/**WARN*/
	public Msg fI(String txt,String insert,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"insertion\":\""+insert+"\",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[5]+"}"); return this;
	}

	/**WARN*/
	public Msg fI(String txt,String insert){
		e.append(",{\"text\":\""+txt+"\",\"insertion\":\""+insert+"\""+f[5]+"}"); return this;
	}

	/**WARN*/
	public Msg f(String txt){
		e.append(",{\"text\":\""+txt+"\""+f[5]+"}"); return this;
	}

	/**WARN*/
	public Msg f(String txt,String tooltip){
		e.append(",{\"text\":\""+txt+"\",\"hoverEvent\":{\"action:\":\"show_text\",\"value\":\""+tooltip+"\"}"+f[5]+"}"); return this;
	}

	/**@param s ",{..}"*/
	public Msg insertJson(String s){
		e.append(s); return this;
	}

	public static void missArg(User a,String b,Player p){
		new Msg(a,b).b("Missing command argument.").a(p);
	}

	public static void missTarget(User a,String b,Player p){
		new Msg(a,b).b("Command target not found.").a(p);
	}

	private String build(){
		e.append("]"); return e.toString();
	}
}
