/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.extension;

import java.util.HashMap;

import de.jan9103.wargearcore.extension.vars.CVar;
import de.jan9103.wargearcore.extension.vars.IntVar;

public class VarSet {
	private final HashMap<String,CVar>local=new HashMap<>();
	private final Extension ext;
	public CVar acc=new IntVar();
	public VarSet(Extension e){
		ext=e;
	}

	public void set(String key,CVar value){
		if(value==null){
			if(local.remove(key)!=null) ext.extVars.remove(key);
		}
		else local.put(key,value);
	}

	public CVar get(String key){
		CVar v=local.getOrDefault(key,null);

		if(v!=null) return v;

		v=ext.extVars.getOrDefault(key,null);
		if(v!=null) return v;

		v=new IntVar();
		local.put(key,v);
		return v;
	}
}
