/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.worldedit;

import java.util.HashSet;

import org.bukkit.block.Block;
import org.bukkit.block.Sign;
import org.bukkit.craftbukkit.v1_19_R3.CraftWorld;
import org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.player.PlayerInteractEvent;

import de.jan9103.wargearcore.User;
import de.jan9103.wargearcore.UserManager;
import de.jan9103.wargearcore.WGC;
import de.jan9103.wargearcore.chat.Msg;
import de.jan9103.wargearcore.jsvn.ScriptBinary;
import de.jan9103.wargearcore.listener.ClickListener;
import de.jan9103.wargearcore.util.WGCAuth;
import net.minecraft.core.BlockPosition;
import net.minecraft.network.protocol.game.PacketPlayOutOpenSignEditor;
import net.minecraft.world.level.block.entity.TileEntitySign;

public class AxeListener implements Listener {
	public static final HashSet<Player>book=new HashSet<>();
	@EventHandler public void onInteract(PlayerInteractEvent e){
		if(WGCAuth.locked.containsKey(e.getPlayer())){
			e.setCancelled(true);
			return;
		}
		if(e.getItem()==null) return;

		final Player p=e.getPlayer();

		switch(e.getItem().getType()){
		case GOLDEN_HOE: break;                                                 // WORLEDIT AXE

		case WRITABLE_BOOK:                                                     // SCRIPT
			switch(e.getAction()){
			case RIGHT_CLICK_BLOCK:
			case RIGHT_CLICK_AIR:
				book.add(p);
				return;

			case LEFT_CLICK_BLOCK:
			case LEFT_CLICK_AIR:
				e.setCancelled(true);
				if(book.remove(p)) return;

				ScriptBinary.run(e.getItem(),p);

			default:
			}
			return;

		case GLISTERING_MELON_SLICE: {                                          // PC
			switch(e.getAction()){
			case RIGHT_CLICK_AIR:
			case RIGHT_CLICK_BLOCK:
			case LEFT_CLICK_AIR:
			case LEFT_CLICK_BLOCK:
				break;

			default: return;
			}
			if(!p.hasPermission("wgc.util.pc")) return;

			final User u=UserManager.getUser(p);
			u.portc.onClick(p);
			e.setCancelled(true);
			return;
		}

		case SHEARS: ClickListener.a(e); return;                        // FERNZUENDER

		default: return;
		}
		final Block b=e.getClickedBlock();
		final User  u=UserManager.getUser(p);

		if(u==null) return;

		if(b==null) return;

		if(e.getAction()==Action.LEFT_CLICK_BLOCK){
			u.getWE().setA(b);
			new Msg(u,WGC._PREFIX_2_Edit).a("Pos a set.").a(p);
		}
		else if(e.getAction()==Action.RIGHT_CLICK_BLOCK){
			u.getWE().setB(b);
			new Msg(u,WGC._PREFIX_2_Edit).a("Pos b set.").a(p);
		}
		e.setCancelled(true);
	}
}
