/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.util;

import de.jan9103.java.utils.Curl;

import java.net.MalformedURLException;

public class DWHS {
	public DWHS(String url,String username,String avatarurl,String text)throws Throwable {
		final JSONObject o=new JSONObject();

		o.put("username",username);
		o.put("content",text.replace("\\","\\\\").replace("\n","\\n").replace("\b","\\b").replace("\"","\\\"").replace("\t","\\t"));
		o.put("avatar_url",avatarurl);
		o.put("tts",false);
		try {
			//final URL u=new URL(url);
			//final HttpsURLConnection con=(HttpsURLConnection)u.openConnection();
			//con.addRequestProperty("Content-Type","application/json");
			//con.addRequestProperty("User-Agent","Java-DiscordWebhook");
			//con.setDoOutput(true);
			//con.setRequestMethod("POST");
			//final OutputStream str=con.getOutputStream();
			//str.write(o.toString().getBytes());
			//str.flush();
			//str.close();
			//con.getInputStream().close();
			//con.disconnect();
			Curl.httpsPost(url,new String[0][0],"application/json",o.toString());
		}catch(final MalformedURLException e){throw new Throwable();}
		//}catch(final ProtocolException e){throw new Throwable();
		//}catch(final IOException e){throw new Throwable();}
	}
}
