/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.util;

public class UUIDstatics {
	public static boolean[] a(String id){
		switch(id){                                                                                                        //														DEV		WT	PH		ISA			CB	SW		PP
		case "19cf4993-252c-4c68-8826-926d065acb4a": return new boolean[] {true,true,true,true,false,true,true,false};     //Jan9103

		case "f75632be-e3ec-4069-9bec-d13ac6891177": return new boolean[] {true,true,false,false,false,true,true,false};   //YoyoNow

		case "719e66a0-52df-497f-a244-9a2dda81b182": return new boolean[] {true,false,false,false,false,false,true,false}; //Lixfel

		case "89bec43a-97bb-4359-b871-2d8fb3dad891": return new boolean[] {true,false,false,false,false,true,false,false}; //Maatthias

		case "b196e0a0-72d5-42d9-a228-136228878ddd": return new boolean[] {true,false,false,false,false,false,true,false}; //chaoscaot

		case "e03b0da-de94-d48f-e8f1-78e2ae9f9029e": return new boolean[] {true,false,false,false,false,false,true,false}; //Zeanon

		//																DEV		WT	PH		ISA			CB	SW		PP

		/*case"24eeddd3-38ca-49bd-ab35-888dedf1f048":return new boolean[]{false,true ,false,false,false,false,true ,false};//Kaltenstein
		 * case"44ff6673-6469-4593-8dba-34226b6049ad":return new boolean[]{false,true ,false,false,false,false,false,false};//Miny__
		 * case"3bd2ca27-000a-467f-9a2d-5d7b3b78abac":return new boolean[]{false,true ,false,false,false,false,false,false};//Todesstimme
		 * case"38fc1498-addd-4392-844f-5286d11f96f3":return new boolean[]{false,true ,false,false,false,false,false,false};//Geegnaz
		 * case"3ee8e00b-ec92-4bd2-a224-086764e1f1bf":return new boolean[]{false,true ,false,false,false,false,false,false};//Ghost4Rider
		 * case"818a2408-fd50-40c5-b866-e312e0d4b95b":return new boolean[]{false,true ,false,false,false,false,false,false};//Kannmichmal
		 * case"3545ea33-dc4b-439a-a2a0-57fbdeb952ba":return new boolean[]{false,true ,false,false,false,false,false,false};//Painter
		 * case"3e61b92f-9d5d-433f-a6d1-e69f65994b2f":return new boolean[]{false,true ,false,false,false,false,false,false};//Core Gamer
		 * case"c79e076-6658-64d5-2961-9803210d54b34":return new boolean[]{false,true ,false,false,false,false,true ,false};//FoehnX
		 * case"e3fc9b9-5a78-74e0-2b6a-99bc90cf0e7a1":return new boolean[]{false,true ,false,false,false,false,false,false};//Eldorin
		 * case"d55bb46-5bc1-f420-9b89-fc72d8a4aeb9e":return new boolean[]{false,true ,false,false,false,false,false,false};//Hund2605
		 * case"09b59c8-1bab-9433-88b1-8967ba01b0012":return new boolean[]{false,true ,false,false,false,false,false,false};//Juvo12
		 * case"46884c1-0dec-f450-a893-1e6693dbee71c":return new boolean[]{false,true ,false,false,false,false,false,false};//ourzo97
		 * //Not found: SpinningBlake
		 * case"38928ef-8c30-b42a-b90a-2bad6261a0b1b":return new boolean[]{false,true ,false,false,false,false,false,false};//FloJo*/
		//	SW															DEV		WT	PH		ISA			CB	SW		PP

		/*case"ff891eb3-8494-4265-94a0-debd1a0834ce":return new boolean[]{false,false,false,false,false,false,true ,false};//Lapis
		 * case"6f2a5333-6a54-41b1-b3d9-eec014f3bbdf":return new boolean[]{false,false,false,false,false,false,true ,false};//maybe
		 * case"4dcced4c-a724-4088-8141-c3e7aa36b032":return new boolean[]{false,false,false,false,false,false,true ,false};//legula
		 * case"f20a345a-a5d9-42ca-be8f-e932a231e339":return new boolean[]{false,false,false,false,false,false,true ,false};//seekrank
		 * case"a71db659-300a-4b23-b935-5cced780d7fe":return new boolean[]{false,false,false,false,false,false,true ,false};//giasa
		 * case"4179469-5b9e-a466-8bff-b9ecacb027b81":return new boolean[]{false,false,false,false,false,false,true ,false};//Tim16227
		 * case"d9e6dd0-1360-34fd-faa3-bdd35546b82b6":return new boolean[]{false,false,false,false,false,false,true ,false};//Schoko3001
		 * case"7cce0c6-c841-64e6-0b54-7042b2d796a41":return new boolean[]{false,false,false,false,false,false,true ,false};//Sehfxhler
		 * case"4dbe97f-326a-a458-085f-b2c81c4e460e1":return new boolean[]{false,false,false,false,false,false,true ,false};//xJoul
		 * case"5cb572f-10b0-444a-a93a-8c483e50ea14a":return new boolean[]{false,false,false,false,false,false,true ,false};//Katze4sekrad
		 * case"f297a2d-c80b-341a-1abe-fa4e2571b777f":return new boolean[]{false,false,false,false,false,false,true ,false};//ByVentrox1337
		 * case"cb9d858-42ff-94b7-d876-121f1cb4c3134":return new boolean[]{false,false,false,false,false,false,true ,false};//LordMainex
		 * case"292e7db6-f11d-42a8-bc6c-654523843ced":return new boolean[]{false,false,false,false,false,false,true ,false};//einfachButzi
		 * //Not found: DrWagenknecht
		 * case"14569c7-b91f-f44b-eacf-b30d8c98929b4":return new boolean[]{false,false,false,false,false,false,true ,false};//Edmund_Strong*/
		// PP															DEV		WT	PH		ISA			CB	SW		PP

		/*case"840781b-8fb3-7445-6bc5-0515e1c96c77c":return new boolean[]{false,false,false,false,false,false,false,true };//Tischkante
		*  case"c6d652c-ecb2-4421-e987-8142c8b3e2bb6":return new boolean[]{false,false,false,false,false,false,false,true };//LUF3N
		*  case"b6225c3-6fe1-44e8-da32-d1d93638d221c":return new boolean[]{false,false,false,false,false,false,false,true };//Firetube_
		*  case"82cdfa7-bcb6-6417-38b9-ca7ce1fffd05c":return new boolean[]{true ,false,false,false,false,false,false,true };//FREE2WIN
		*  case"165dffe-b14d-8471-994b-f422dc8618aab":return new boolean[]{true ,false,false,false,false,false,false,true };//McTNTCrafter
		*  case"b51f08e-2ed5-043b-c8f8-751675b4b50c1":return new boolean[]{true ,false,false,false,false,false,false,true };//ZentornoLP
		*  case"c6f2718-270a-d4b3-1a73-fe1d108233604":return new boolean[]{true ,false,false,false,false,false,false,true };//Postremus
		*  case"d132617-10bc-34b4-4904-8a30d21139319":return new boolean[]{true ,false,false,false,false,false,false,true };//JAB_1305
		*  case"57827f4-881b-a4b8-e9bf-d9e631783be27":return new boolean[]{true ,false,false,false,false,false,false,true };//Lukas3482
		*  case"9e45591-9f7e-24cc-9994-c42f487d035a8":return new boolean[]{true ,false,false,false,false,false,false,true };//MoritzR200
		*  case"978fe81-d14e-e49c-f95c-c4d0c4105b348":return new boolean[]{false,false,false,false,false,false,false,true };//Coernerbrot
		*  case"cc49f3f-8f47-b4c8-5b5f-0bef7cbcc0790":return new boolean[]{false,false,false,false,false,false,false,true };//Brain23413
		*  case"4e979fe-e473-24f3-6875-863b3e17c6f26":return new boolean[]{false,false,false,false,false,false,false,true };//Buffi_TV
		*  case"66b374c-5d37-947f-7b84-5a0f5f8375a0a":return new boolean[]{false,false,false,false,false,false,false,true };//Lucas3101
		*  case"df114ae-c1e4-d44d-2b00-3a7c082fb799f":return new boolean[]{false,false,false,false,false,false,false,true };//Blober
		*  case"408c2f3-755d-b413-db5b-a99bc82d9cdd1":return new boolean[]{false,false,false,false,false,false,false,true };//xBushman99x
		*  case"ebd4551-c91c-d4e7-c902-35f4ebd09ae4a":return new boolean[]{false,false,false,false,false,false,false,true };//Minecraft_Stube
		*  case"b3c18f9-17a7-34df-ea23-79779fc8cd0d0":return new boolean[]{false,false,false,false,false,false,false,true };//Nelcon
		*  case"266ee4f-59a3-749d-f9d6-817701fca5f0d":return new boolean[]{false,false,false,false,false,false,false,true };//thelongway
		*  case"8191700-c841-2414-eb3c-220687ac18ad7":return new boolean[]{false,false,false,false,false,false,false,true };//The_Cryptokid
		*  case"c736f93-0c61-14e0-3bad-5a112600133cc":return new boolean[]{false,false,false,false,false,false,false,true };//TheDark_Beat
		*  case"361b63b-ffda-24d2-ba38-b14fe0d355a28":return new boolean[]{false,false,false,false,false,false,false,true };//Doktor_Mart
		*  case"fe97ec7-dc5b-c43b-9a50-781ff931f412f":return new boolean[]{false,false,false,false,false,false,false,true };//Phieper
		*  case"d4f4f58-2f26-c40d-c96f-3784dc0c15936":return new boolean[]{false,false,false,false,false,false,false,true };//Officer_LeyLey
		*  case"54115e7-81bd-44c1-a905-a752b25993c56":return new boolean[]{false,false,false,false,false,false,false,true };//onlyZean
		*  case"dbd0019-dc56-643b-f8dc-df8c9b53b6e7e":return new boolean[]{false,false,false,false,false,false,false,true };//FloHash
		*  case"d8f3bc1-848e-64f5-e8a9-63b20cd03392f":return new boolean[]{false,false,false,false,false,false,false,true };//Paulus2014*/
		//  PH															DEV		WT	PH		ISA			CB	SW		PP

		/*case"3aa2f8f-b6f1-b47c-2bfc-25a53ff008283":return new boolean[]{false,false,true ,false,false,false,false,false};//Schmerz_YT
		 * case"4f59281-fc3f-d4b6-8ba2-d4e7615de8186":return new boolean[]{false,false,true ,false,false,false,false,false};//KinglyDegre391
		 * case"8f7565d-589d-d4cd-1a3d-1a89c9ffdc327":return new boolean[]{false,false,true ,false,false,false,false,false};//JajaKings
		 * case"e71c14e-8192-947e-7bb9-25e4e56219311":return new boolean[]{false,false,true ,false,false,false,false,false};//zSalos*/
		//	ISA															DEV		WT	PH		ISA			CB	SW		PP

		/*case"fcbda5e0-19d9-46a4-92f6-2d1e5ecee694":return new boolean[]{false,false,false,true ,false,false,false,false};//_Malido
		 * case"77ec43d5-2adf-4d84-8238-c36a6151cf15":return new boolean[]{false,false,false,true ,false,false,false,false};//Till__
		 * case"55d30b56-873b-423c-a6c5-a312b7985f4e":return new boolean[]{false,false,false,true ,false,false,false,false};//WaliTV
		 * case"a1a17452-bd43-4783-9958-951739685c1c":return new boolean[]{false,false,false,true ,false,false,false,false};//KawaHD
		 * case"5a676037-f34c-4498-ac1b-27e2b556630f":return new boolean[]{false,false,false,true ,false,false,false,false};//Brot__
		 * case"5924e24a-c96a-4017-89bc-ed4c1c7dfbfc":return new boolean[]{false,false,false,true ,false,false,false,false};//unlikehybrid
		 * case"ecc21094-c3b5-4bd6-af41-af981d3db729":return new boolean[]{false,false,false,true ,false,false,false,false};//xxmlgaminxx
		 * case"5e58a417-b0d3-468f-9cb6-265c4d5195ec":return new boolean[]{false,false,false,true ,false,false,false,false};//punse_
		 * case"c2127f80-a2d1-4117-bd97-a93736eb3d61":return new boolean[]{false,false,false,true ,false,false,false,false};//parisachill
		 * case"07c91d45-d683-457d-abf3-44a042a79600":return new boolean[]{false,false,false,true ,false,false,false,false};//sixtus18*/
		//	DPR															DEV		WT	PH		ISA			CB	SW		PP
		case "8577bcf4-19cf-453e-8002-32092efd3db8": return new boolean[] {false,false,false,false,false,true,false,false};      //TheBreadBeard

		//    KNORK31
		//																DEV		WT	PH		ISA			CB	SW		PP
		default:                                                                   return new boolean[] {false,false,false,false,false,false,false,false};
		}
	}
}
