/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.jsvn;

import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.entity.Player;

import de.jan9103.wargearcore.User;
import de.jan9103.wargearcore.WGC;
import de.jan9103.wargearcore.chat.Msg;
import de.jan9103.wargearcore.coordSys.BigArea;
import de.jan9103.wargearcore.worldedit.editors.async.AsyncRepOtO;

public class WgeRepCmd extends Cmd {
	private byte e;
	private final ScriptMaterial a,k;
	public WgeRepCmd(ScriptMaterial c,ScriptMaterial d,byte f){
		a=c; k=d; e=f;
	}

	public WgeRepCmd(String[] c)throws ParseException {
		//WGE REP (mat) (mat) <range>
		if(c.length<4) throw new ParseException("WGE REP misses arguments..");
		a=new ScriptMaterial(c[2]);
		k=new ScriptMaterial(c[3]);
		if(c.length==5) try{e=Byte.parseByte(c[4]);}catch(final NumberFormatException e){throw new ParseException("WGE-REP: invalid range");}
		else e=0;
	}

	@Override public void run(User u,Player p,Block b,VarSet v){
		Material c,d;

		try{c=a.getWE(v); d=k.getWE(v);}catch(final NullPointerException e){new Msg(u,WGC._PREFIX_2_Script).b("Invalid materials used in replace..").a(p); return;}
		final BigArea f=e==0?u.getWE().toBigArea():new BigArea(b.getX()-e,b.getY()-e,b.getZ()-e,b.getX()+e,b.getY()+e,b.getZ()+e);

		new AsyncRepOtO(b.getWorld(),f,c,d,false,u).a();
	}
}
