/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.worldedit.editors.async;

import org.bukkit.World;
import org.bukkit.block.Block;
import org.bukkit.block.TileState;
import org.bukkit.craftbukkit.v1_19_R3.CraftWorld;

import de.jan9103.wargearcore.area.ATheme;
import de.jan9103.wargearcore.area.ATheme.THM;
import de.jan9103.wargearcore.coordSys.BigCoord;
import de.jan9103.wargearcore.worldedit.clip.Clipboard;
import de.jan9103.wargearcore.worldedit.clip.ClipboardBlock;
import de.jan9103.wargearcore.worldedit.clip.TCB;
import de.jan9103.wargearcore.worldedit.editors.Undo;
import de.jan9103.wargearcore.worldedit.editors.WeSender;
import net.minecraft.core.BlockPosition;

/**
 * ONLY CALL ASYNC !!
 */
public class AsyncPaste4b extends AsyncEditor3 {
	private final CraftWorld cw;
	private Clipboard c;
	private final ATheme.THM at;
	public AsyncPaste4b(World world,BigCoord pos,WeSender source,Clipboard cb){
		super(world,pos.toAr(1,1,1),false,source); cw=(CraftWorld)world; c=cb; at=ATheme.THM.GRAY;
	}

	@Override public void exe(int xl2,int xh,int yl2,int yh,int zl2,int zh){
		final THM thm1=c.thm1(at),thm2=c.thm2(at);

		for(int x=xl2; x<=xh; x++)
			for(int y=yl2; y<=yh; y++)
				for(int z=zl2; z<=zh; z++){
					final ClipboardBlock b=c.clip[x-xl][y-yl][z-zl];
					if(b==null) continue;
					final Block a=w.getBlockAt(x,y,z);
					//if(a.getState() instanceof TileState) cw.getHandle().removeTileEntity(new BlockPosition(x,y,z));
					if(b instanceof TCB){
						((TCB)b).blockPaste(w.getBlockAt(x,y,z),thm1,thm2,true); continue;
					}
					b.blockPaste(w.getBlockAt(x,y,z));
				}
	}

	@Override public boolean b(){
		if(c==null) return false;

		xl +=c.cv.x;
		yl +=c.cv.y;
		zl +=c.cv.z;
		xh  =xl+c.xSize()-1;
		yh  =yl+c.ySize()-1;
		zh  =zl+c.zSize()-1;
		x   =xl; y=yl; z=zl;
		cxl =xl; czl=zl;
		cxh =Integer.min(xh,x+15); czh=Integer.min(zh,z+15);
		chun=w.getChunkAt(x>>4,z>>4);
		return true;
	}

	@Override public void prepUndo(Undo i){
		if(c==null) return;

		int xl=this.xl+c.cv.x,
		    yl=this.yl+c.cv.y,
		    zl=this.zl+c.cv.z,
		    xh=this.xl+c.xSize(),
		    yh=this.yl+c.ySize(),
		    zh=this.zl+c.zSize();

		i.sA(xl,xh,yl,yh,zl,zh,w);
	}

	@Override public int[] area(){
		if(c==null) return new int[] {xl,xh,yl,yh,zl,zh};
		int xl=this.xl+c.cv.x,
		    yl=this.yl+c.cv.y,
		    zl=this.zl+c.cv.z,
		    xh=this.xl+c.xSize(),
		    yh=this.yl+c.ySize(),
		    zh=this.zl+c.zSize();

		return new int[] {xl,xh,yl,yh,zl,zh};
	}
}
