/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.cmds;

import java.util.ArrayList;

import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BookMeta;

import de.jan9103.wargearcore.User;
import de.jan9103.wargearcore.chat.Msg;

public class BookColor extends UserOnlyCmd {
	@Override public void exe(String[] a,User u,Player p){
		final ItemStack i=p.getInventory().getItemInMainHand();

		if(i==null){
			new Msg(u).b("You have to have a book selected in your main-hand.").a(p); return;
		}
		if(i.getType()!=Material.WRITABLE_BOOK&&i.getType()!=Material.WRITTEN_BOOK){
			new Msg(u).b("Thats not a book.").a(p); return;
		}
		final BookMeta m=(BookMeta)i.getItemMeta();

		if(!m.hasPages()){
			new Msg(u).b("The book is empty..").a(p); return;
		}
		final ArrayList<String>q=new ArrayList<>();

		for(final String z:m.getPages()) q.add(z.replace("&&","%/(/TGZUFTGZUHIGGZ").replace('&','§').replace("%/(/TGZUFTGZUHIGGZ","&"));
		m.setPages(q);
		i.setItemMeta(m);
		new Msg(u).a("Book colored.").a(p);
	}
}
