/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.cmds;

import org.bukkit.GameMode;
import org.bukkit.entity.Player;

import de.jan9103.wargearcore.User;
import de.jan9103.wargearcore.chat.Msg;

public class GamemodeCmds extends UserOnlyCmd {
	@Override public void exe(String[] a,User u,Player p){
		System.out.println("GAMEMODE");
		if(a.length<1){
			if(p.getGameMode()==GameMode.CREATIVE){
				p.setGameMode(GameMode.SPECTATOR);
				new Msg(u).a("Cycled gamemode to ").c("Spectator").a(".").a(p);
			}
			else{
				p.setGameMode(GameMode.CREATIVE);
				new Msg(u).a("Cycled gamemode to ").c("Creative").a(".").a(p);
			}
			return;
		}
		User t=u;

		if(a.length>1){
			t=parseTarget(a[1]);
			if(t==null){
				new Msg(u).b("Invalid target.").a(p); return;
			}
		}
		GameMode gm;

		switch(a[0].toLowerCase()){
		case "s":
		case "survival":
		case "0":
			gm=GameMode.SURVIVAL;
			break;

		case "c":
		case "creative":
		case "1":
		case "kaltenstein":
			gm=GameMode.CREATIVE;
			break;

		case "a":
		case "adventure":
		case "2":
			gm=GameMode.ADVENTURE;
			break;

		case "w":
		case "spectator":
		case "watch":
		case "3":
			gm=GameMode.SPECTATOR;
			break;

		default:
			new Msg(u).b("Invalid gamemode.").a(p);
			return;
		}
		if(t==u)
			if(p.getGameMode()==gm){
				if(gm==GameMode.CREATIVE) gm=GameMode.SPECTATOR;
				else gm=GameMode.CREATIVE;
			}
		t.gm(gm);
		String b;

		switch(gm){
		case SURVIVAL: b="Survival"; break;

		case CREATIVE: b="Creative"; break;

		case ADVENTURE: b="Adventure"; break;

		default: b="Spectator";
		}
		if(u!=t){
			new Msg(u).a("Switched ").c(t.getName()).a("'s gamemode to ").c(b).a(p);
			new Msg(t).c(p.getName()).a(" switched your gamemode to ").c(b).a(".").a(t);
		}
		else new Msg(u).a("Switched to gamemode ").c(b).a(".").a(p);
	}
}
