/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.cmds;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;

import de.jan9103.wargearcore.util.TPS;

public class TpsCmd implements CommandExecutor {
	@Override public boolean onCommand(CommandSender s,Command arg1,String arg2,String[] a){
		final Runtime r=Runtime.getRuntime();
		final long    tot=r.totalMemory(),fre=r.freeMemory();
		final long    use=tot-fre;
		final double  per=(double)use/tot*100;

		s.sendMessage(
			"§8############# §7Performance §8###########§7"+
			"\nDUE TO UNKNOWN REASONS THE TPS IS OFTEN WRONG IF THE TPSLIMITER IS ON ! im working on it.."+
			"\nWGC-TPS: "+TPS.a()+
			"§7\nRAM:       "+ram(per,"%")+
			"\n####################################"
			);
		return true;
	}

	private String ram(double i,String eh){
		switch((int)(Math.round(i)/10)){
		case 1: return "§8[§a#---------§8] (§a"+form(i)+eh+"§8)";

		case 2: return "§8[§a##--------§8] (§a"+form(i)+eh+"§8)";

		case 3: return "§8[§a###-------§8] (§a"+form(i)+eh+"§8)";

		case 4: return "§8[§a####------§8] (§a"+form(i)+eh+"§8)";

		case 5: return "§8[§e#####-----§8] (§e"+form(i)+eh+"§8)";

		case 6: return "§8[§6######----§8] (§6"+form(i)+eh+"§8)";

		case 7: return "§8[§6#######---§8] (§6"+form(i)+eh+"§8)";

		case 8: return "§8[§c########--§8] (§c"+form(i)+eh+"§8)";

		case 9: return "§8[§c#########-§8] (§c"+form(i)+eh+"§8)";

		default:
			if((byte)i>60) return "§8[§4##########§8] (§4"+form(i)+eh+"§8)";

			return "§8[§2----------§8] (§2"+form(i)+eh+"§8)";
		}
	}

	/*private String invbar(double i,String eh){
	 *      switch(((int)(Math.round(i)/10))){
	 *              case 1:return"§8[§a#---------§8] (§a"+form(i)+eh+"§8)";
	 *              case 2:return"§8[§e##--------§8] (§e"+form(i)+eh+"§8)";
	 *              case 3:return"§8[§e###-------§8] (§e"+form(i)+eh+"§8)";
	 *              case 4:return"§8[§6####------§8] (§6"+form(i)+eh+"§8)";
	 *              case 5:return"§8[§6#####-----§8] (§6"+form(i)+eh+"§8)";
	 *              case 6:return"§8[§c######----§8] (§c"+form(i)+eh+"§8)";
	 *              case 7:return"§8[§c#######---§8] (§c"+form(i)+eh+"§8)";
	 *              case 8:return"§8[§4########--§8] (§4"+form(i)+eh+"§8)";
	 *              case 9:return"§8[§4#########-§8] (§4"+form(i)+eh+"§8)";
	 *              default:
	 *                      if((byte)i>60)return"§8[§4##########§8] (§4"+form(i)+eh+"§8)";
	 *                      return "§8[§2----------§8] (§2"+form(i)+eh+"§8)";
	 *              }
	 * }*/
	public static String form(Double i){
		return String.format("%.2f",i);
	}
}
