/*
 * Copyright 2021 Jan9103 (@jan9103:matrix.org Jan9103.wargear@protonmail.com)
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 * and to permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
package de.jan9103.wargearcore.area;

/**
 * themed material names
 */
public enum ThemeMat { // 2*57 = 114 per schem
	OWN_DARK,
	OWN_LIGHT,
	OWN_MARKER,
	OWN_SAND,
	OWN_SLAB,
	OWN_SLAB_HIGH,
	OWN_GATE,
	OWN_THIN_SHIELD,
	OWN_BANNER_DARK,
	OWN_BANNER_LIGHT,
	OWN_CARPET_LIGHT,
	OWN_CARPET_DARK,
	OWN_CONCRETE_LIGHT,
	OWN_CONCRETE_DARK,
	OWN_GLASS_LIGHT,
	OWN_GLASS_DARK,
	OWN_PANE_LIGHT,
	OWN_PANE_DARK,
	OWN_POWDER_LIGHT,
	OWN_POWDER_DARK,
	OWN_SHULKER_LIGHT,
	OWN_SHULKER_DARK,
	OWN_GLAZED_LIGHT,
	OWN_GLAZED_DARK,
	OWN_TERRA_LIGHT,
	OWN_TERRA_DARK,
	OWN_ARENA,
	ENEMY_DARK,
	ENEMY_LIGHT,
	ENEMY_MARKER,
	ENEMY_SAND,
	ENEMY_SLAB,
	ENEMY_SLAB_HIGH,
	ENEMY_GATE,
	ENEMY_THIN_SHIELD,
	ENEMY_BANNER_DARK,
	ENEMY_BANNER_LIGHT,
	ENEMY_CARPET_LIGHT,
	ENEMY_CARPET_DARK,
	ENEMY_CONCRETE_LIGHT,
	ENEMY_CONCRETE_DARK,
	ENEMY_GLASS_LIGHT,
	ENEMY_GLASS_DARK,
	ENEMY_PANE_LIGHT,
	ENEMY_PANE_DARK,
	ENEMY_POWDER_LIGHT,
	ENEMY_POWDER_DARK,
	ENEMY_SHULKER_LIGHT,
	ENEMY_SHULKER_DARK,
	ENEMY_GLAZED_LIGHT,
	ENEMY_GLAZED_DARK,
	ENEMY_TERRA_LIGHT,
	ENEMY_TERRA_DARK,
	ENEMY_ARENA,
	ARENA_HIGHLIGHT
}
